#!/usr/bin/env python3
"""Tests for scripts/check-no-ai-attribution.py + check-author-not-bot.py.

Run from the repository root:
    python3 scripts/test_ai_attribution.py

Exits non-zero on any failure. No external test runner required.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Iterable, List

_SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS))

import ai_attribution_patterns as catalog  # type: ignore  # noqa: E402


def _load(filename: str):
    spec = importlib.util.spec_from_file_location(
        filename.replace("-", "_").replace(".py", ""),
        _SCRIPTS / filename,
    )
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_main = _load("check-no-ai-attribution.py")
_author = _load("check-author-not-bot.py")
scan = _main.scan
scan_identity = _author.scan_identity


_failures: List[str] = []


def expect(condition: bool, label: str) -> None:
    if condition:
        print(f"PASS: {label}")
    else:
        print(f"FAIL: {label}", file=sys.stderr)
        _failures.append(label)


def labels(violations: Iterable) -> List[str]:
    return [v[1] for v in violations]


# ─── Catalog integrity ───────────────────────────────────────────────────

for _name in ("attribution_trailers", "generated_by_attribution",
              "robot_emoji", "branding_brackets", "vendor_emails"):
    expect(len(catalog.HARD_RULES[_name]) > 0,
           f"catalog HARD_RULES[{_name!r}] non-empty")

for _name in ("llm_names", "agent_names"):
    expect(len(catalog.SOFT_RULES[_name]) > 0,
           f"catalog SOFT_RULES[{_name!r}] non-empty")

for _name in ("bot_names", "bot_emails"):
    expect(len(catalog.AUTHOR_RULES[_name]) > 0,
           f"catalog AUTHOR_RULES[{_name!r}] non-empty")

expect(len(catalog.CONTEXT_ANCHORS) > 0,
       "catalog CONTEXT_ANCHORS non-empty")


# ─── Clean cases ─────────────────────────────────────────────────────────

expect(scan("") == [],
       "empty message produces no violations")

expect(scan("feat: (auth) wire OIDC middleware\n\nRefs #15") == [],
       "a normal commit message produces no violations")

expect(scan("# Please enter the commit message...\n# stripped lines") == [],
       "comments-only message is clean")

expect(scan("feat: (gemini-embedder) wire Gemini API calls") == [],
       "Gemini in feature scope (no attribution context) passes")

expect(scan("fix: handle Claude API rate-limit response") == [],
       "Claude in bug fix prose (no attribution context) passes")

expect(scan("refactor: extract OpenAI provider client") == [],
       "OpenAI in refactor prose passes")

expect(scan("docs: update CLAUDE.md to add new section") == [],
       "CLAUDE.md filename is exempt")

expect(scan("fix: drop reference to claudeService") == [],
       "camelCase identifier 'claudeService' is not flagged")


# ─── Hard violations: attribution trailers ───────────────────────────────

violations = scan("feat: x\n\nCo-Authored-By: Alice <alice@example.com>")
expect("Co-Authored-By trailer (any value)" in labels(violations),
       "Co-Authored-By: even with HUMAN value triggers (sole-author rule)")

expect("Generated-By trailer" in labels(scan("Generated-By: someone")),
       "Generated-By trailer triggers")

expect("Assisted-By trailer" in labels(scan("Assisted-By: someone")),
       "Assisted-By trailer triggers")


# ─── Hard violations: Generated/Powered/AI-assisted markers ──────────────

expect("'Generated with/by/using X' attribution"
       in labels(scan("Generated with some-tool")),
       "'Generated with X' triggers")

expect("'Generated with/by/using X' attribution"
       in labels(scan("Generated by some-tool")),
       "'Generated by X' triggers")

expect("'Generated with/by/using X' attribution"
       in labels(scan("Generated using some-tool")),
       "'Generated using X' triggers")

expect("'Powered by X' attribution"
       in labels(scan("Powered by some-tool")),
       "'Powered by X' triggers")

expect("AI/LLM-assisted/generated marker"
       in labels(scan("This change is AI-assisted")),
       "'AI-assisted' triggers")

expect("AI/LLM-assisted/generated marker"
       in labels(scan("AI-generated patch")),
       "'AI-generated' triggers")

expect("'Authored by AI/LLM/agent/bot' attribution"
       in labels(scan("authored by an agent")),
       "'authored by an agent' triggers")


# ─── Hard violations: robot emoji ────────────────────────────────────────

expect("robot emoji \U0001F916" in labels(scan("\U0001F916 generated patch")),
       "robot emoji triggers")


# ─── Hard violations: branding brackets ──────────────────────────────────

bracket_cases = [
    ("[Claude Code]", "[Claude Code] branding"),
    ("[Cursor]", "[Cursor] branding"),
    ("[Cursor Agent]", "[Cursor] branding"),
    ("[Cursor Composer]", "[Cursor] branding"),
    ("[Cline]", "[Cline] branding"),
    ("[Aider]", "[Aider] branding"),
    ("[Devin]", "[Devin] branding"),
    ("[Sweep]", "[Sweep] branding"),
    ("[CodeRabbit]", "[CodeRabbit] branding"),
    ("[Continue]", "[Continue] branding"),
    ("[Cody]", "[Cody] branding"),
    ("[Copilot]", "[Copilot] branding"),
    ("[Copilot Workspace]", "[Copilot] branding"),
    ("[Codeium]", "[Codeium] branding"),
    ("[Windsurf]", "[Windsurf] branding"),
    ("[Tabnine]", "[Tabnine] branding"),
    ("[v0.dev]", "[v0.dev] branding"),
    ("[Bolt.new]", "[Bolt.new] branding"),
    ("[Replit AI]", "[Replit AI/Agent] branding"),
    ("[Replit Agent]", "[Replit AI/Agent] branding"),
    ("[Amazon Q]", "[Amazon Q] branding"),
    ("[CodeWhisperer]", "[CodeWhisperer] branding"),
    ("[Augment Code]", "[Augment Code] branding"),
]
for sample, expected_label in bracket_cases:
    expect(expected_label in labels(scan(sample)),
           f"{sample!r} triggers {expected_label!r}")


# ─── Hard violations: vendor emails ──────────────────────────────────────

email_cases = [
    ("noreply@anthropic.com", "@anthropic.com email"),
    ("hello@claude.ai", "@claude.ai email"),
    ("noreply@openai.com", "@openai.com email"),
    ("agent@cursor.so", "Cursor email"),
    ("paul@aider.chat", "Aider email"),
    ("devin@cognition.ai", "Cognition (Devin) email"),
    ("noreply@codeium.com", "Codeium email"),
    ("hi@continue.dev", "Continue.dev email"),
    ("bot@sweep.dev", "Sweep.dev email"),
    ("noreply@coderabbit.ai", "CodeRabbit email"),
    ("dependabot[bot]@users.noreply.github.com",
     "GitHub bot noreply email"),
]
for sample, expected_label in email_cases:
    expect(expected_label in labels(scan(sample)),
           f"{sample!r} triggers {expected_label!r}")


# ─── Soft rules — context-anchored ───────────────────────────────────────

v = scan("feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>")
expect("Anthropic's Claude" in labels(v),
       "Claude inside Co-Authored-By: triggers (soft+context)")

v = scan("Authored by GPT-4")
expect(any("GPT" in lab for lab in labels(v)),
       "'Authored by GPT-4' triggers")

v = scan("written by Llama-3")
expect("Meta Llama" in labels(v),
       "'written by Llama-3' triggers via 'by' anchor")

v = scan("Co-Authored-By: Cursor Agent <agent@cursor.so>")
expect("Cursor Agent/Composer/AI" in labels(v),
       "Cursor Agent in Co-Authored-By line triggers")

v = scan("Switch from GPT-4 to Claude for the explainer")
expect("Anthropic's Claude" not in labels(v),
       "bare prose 'Claude for the explainer' does NOT trigger")
expect("GPT-N model" not in labels(v),
       "bare prose 'GPT-4' does NOT trigger")


# ─── Soft rules — agent names in attribution context ─────────────────────

agent_cases_in_context = [
    ("Co-Authored-By: Aider", "Aider"),
    ("Co-Authored-By: Cline", "Cline"),
    ("Co-Authored-By: Devin", "Cognition Devin"),
    ("Co-Authored-By: Sweep.dev", "Sweep.dev"),
    ("Co-Authored-By: CodeRabbit", "CodeRabbit"),
    ("authored by Codeium", "Codeium"),
    ("authored by AutoGPT", "AutoGPT"),
    ("authored by BabyAGI", "BabyAGI"),
]
for sample, expected_label in agent_cases_in_context:
    expect(expected_label in labels(scan(sample)),
           f"{sample!r} triggers soft label {expected_label!r}")


# ─── Allowlist behaviour ─────────────────────────────────────────────────

v = scan("Co-Authored-By: noreply@anthropic.com")
expect(len(v) > 0, "without allowlist, anthropic email is a violation")

v = scan("Co-Authored-By: noreply@anthropic.com",
         allowlist=["co-authored-by: noreply@anthropic.com"])
expect(v == [],
       "allowlist substring suppresses the violation")

v = scan("Co-Authored-By: noreply@anthropic.com",
         allowlist=["something-else"])
expect(len(v) > 0, "non-matching allowlist substring does not suppress")


# ─── Author identity (check-author-not-bot.py) ───────────────────────────

expect(scan_identity("Alice Engineer", "alice@example.com") == [],
       "human author identity is clean")

v = scan_identity("dependabot[bot]", "dependabot[bot]@users.noreply.github.com")
expect(any(lab == "name ends in [bot]" for _k, lab, *_ in v),
       "[bot] suffix in author name fires")
expect(any(lab == "GitHub bot noreply email" for _k, lab, *_ in v),
       "GitHub bot noreply email fires")

v = scan_identity("Claude", "noreply@anthropic.com")
expect(any(lab == "name starts with 'Claude'" for _k, lab, *_ in v),
       "name 'Claude' fires")
expect(any(lab == "@anthropic.com email" for _k, lab, *_ in v),
       "anthropic.com email fires")

v = scan_identity("bot-deploy", "deploy@example.com")
expect(any(lab == "name starts with 'bot'" for _k, lab, *_ in v),
       "'bot-deploy' name fires")

v = scan_identity("Some User", "user+ai@gmail.com")
expect(any(lab == "+ai sub-address" for _k, lab, *_ in v),
       "'user+ai@' fires")


# ─── Exit ────────────────────────────────────────────────────────────────

if _failures:
    print(f"\n{len(_failures)} TEST(S) FAILED", file=sys.stderr)
    sys.exit(1)
print("\nAll tests passed.")
