package surreal

import (
	"context"
	"fmt"
	"time"

	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"

	"github.com/commit0-dev/commit0/server/internal/domain"
	"github.com/commit0-dev/commit0/pkg/types"
)

// Compile-time check.
var _ domain.TemporalStore = (*SurrealAdapter)(nil)

// UpsertNodeTemporal upserts a node with temporal (commit) metadata.
func (a *SurrealAdapter) UpsertNodeTemporal(ctx context.Context, node *types.CodeNode, commitHash string, commitTime time.Time) error {
	table := nodeTable(string(node.Kind))
	_, localID := splitRecordID(node.ID)
	if localID == "" {
		localID = node.Qualified
	}

	const q = `UPDATE type::record($id) MERGE {
		introduced_commit:    IF introduced_commit IS NONE THEN $commit ELSE introduced_commit END,
		introduced_at:        IF introduced_at IS NONE THEN $ts ELSE introduced_at END,
		last_modified_commit: $commit,
		last_modified_at:     $ts
	};`

	_, err := surrealdb.Query[any](ctx, a.db, q, map[string]any{
		"id":     models.NewRecordID(table, localID),
		"commit": commitHash,
		"ts":     commitTime,
	})
	if err != nil {
		return fmt.Errorf("upsert node temporal %s: %w", node.ID, err)
	}
	return nil
}

// UpsertEdgeTemporal upserts an edge with temporal metadata.
func (a *SurrealAdapter) UpsertEdgeTemporal(ctx context.Context, edge *types.CodeEdge, commitHash string, commitTime time.Time) error {
	table := string(edge.Kind)
	if table == "function" {
		table = "`function`"
	}

	const q = `UPDATE type::record($id) MERGE {
		introduced_commit: IF introduced_commit IS NONE THEN $commit ELSE introduced_commit END,
		introduced_at:     IF introduced_at IS NONE THEN $ts ELSE introduced_at END
	};`

	// Edge IDs in SurrealDB are typically auto-generated by RELATE.
	// We construct an approximate ID from the edge kind + from/to.
	edgeID := fmt.Sprintf("%s:%s->%s", edge.Kind, edge.FromID, edge.ToID)
	_, localID := splitRecordID(edgeID)
	if localID == "" {
		localID = edgeID
	}

	_, err := surrealdb.Query[any](ctx, a.db, q, map[string]any{
		"id":     models.NewRecordID(table, localID),
		"commit": commitHash,
		"ts":     commitTime,
	})
	if err != nil {
		// Non-fatal: edges may not have direct IDs
		a.log.Debug("upsert edge temporal failed", "edge", edgeID, "err", err)
	}
	return nil
}

// MarkNodeRemoved marks a node as removed at a specific commit.
func (a *SurrealAdapter) MarkNodeRemoved(ctx context.Context, nodeID, commitHash string, commitTime time.Time) error {
	table, localID := splitRecordID(nodeID)
	if table == "" || localID == "" {
		return nil
	}

	const q = `UPDATE type::record($id) MERGE {
		removed_commit: $commit
	};`

	_, err := surrealdb.Query[any](ctx, a.db, q, map[string]any{
		"id":     models.NewRecordID(table, localID),
		"commit": commitHash,
	})
	if err != nil {
		return fmt.Errorf("mark node removed %s: %w", nodeID, err)
	}
	return nil
}

// MarkEdgeRemoved marks an edge as removed at a specific commit.
func (a *SurrealAdapter) MarkEdgeRemoved(ctx context.Context, edgeID, commitHash string, commitTime time.Time) error {
	// Edge removal is tracked via metadata — less precise than node removal.
	// For now, this is a no-op since edge IDs are auto-generated by RELATE.
	return nil
}

// QueryTemporalRange returns all changes between two commits for a repo.
func (a *SurrealAdapter) QueryTemporalRange(ctx context.Context, repoSlug, fromCommit, toCommit string) ([]types.TemporalChange, error) {
	params := map[string]any{
		"repo_ref": models.NewRecordID("repo", repoSlug),
	}

	// Query nodes introduced or modified between the two commits
	var changes []types.TemporalChange

	tables := []string{"`function`", "class", "file"}
	for _, table := range tables {
		q := fmt.Sprintf(`SELECT * FROM %s WHERE repo = $repo_ref
			AND (introduced_commit IS NOT NONE OR last_modified_commit IS NOT NONE)
			ORDER BY last_modified_at DESC LIMIT 100;`, table)

		results, err := surrealdb.Query[[]nodeRow](ctx, a.db, q, params)
		if err != nil {
			continue
		}
		if results == nil || len(*results) == 0 {
			continue
		}

		for _, r := range (*results)[0].Result {
			node := rowToCodeNode(r, kindFromTable(table))
			change := types.TemporalChange{
				CommitHash: node.LastModifiedCommit,
				Timestamp:  safeTime(node.LastModifiedAt),
			}
			if node.IntroducedCommit == node.LastModifiedCommit {
				change.NodesAdded = append(change.NodesAdded, node)
			} else {
				change.NodesModified = append(change.NodesModified, node)
			}
			changes = append(changes, change)
		}
	}

	return changes, nil
}

// NodeHistory returns the temporal history of a specific node.
func (a *SurrealAdapter) NodeHistory(ctx context.Context, nodeID string) ([]types.TemporalChange, error) {
	table, localID := splitRecordID(nodeID)
	if table == "" || localID == "" {
		return nil, nil
	}

	const q = `SELECT * FROM type::record($id);`
	results, err := surrealdb.Query[[]nodeRow](ctx, a.db, q, map[string]any{
		"id": models.NewRecordID(table, localID),
	})
	if err != nil {
		return nil, fmt.Errorf("node history %s: %w", nodeID, err)
	}
	if results == nil || len(*results) == 0 || len((*results)[0].Result) == 0 {
		return nil, nil
	}

	r := (*results)[0].Result[0]
	node := rowToCodeNode(r, kindFromTable(table))

	var changes []types.TemporalChange
	if node.IntroducedCommit != "" {
		changes = append(changes, types.TemporalChange{
			CommitHash: node.IntroducedCommit,
			Timestamp:  safeTime(node.IntroducedAt),
			NodesAdded: []types.CodeNode{node},
		})
	}
	if node.LastModifiedCommit != "" && node.LastModifiedCommit != node.IntroducedCommit {
		changes = append(changes, types.TemporalChange{
			CommitHash:    node.LastModifiedCommit,
			Timestamp:     safeTime(node.LastModifiedAt),
			NodesModified: []types.CodeNode{node},
		})
	}

	return changes, nil
}

// EdgesIntroducedAt returns edges introduced in a specific commit.
func (a *SurrealAdapter) EdgesIntroducedAt(ctx context.Context, repoSlug, commitHash string) ([]types.CodeEdge, error) {
	params := map[string]any{"commit": commitHash}

	var edges []types.CodeEdge
	edgeTables := []string{"calls", "data_flow"}
	for _, table := range edgeTables {
		q := fmt.Sprintf("SELECT * FROM %s WHERE introduced_commit = $commit LIMIT 100;", table)
		results, err := surrealdb.Query[[]edgeRow](ctx, a.db, q, params)
		if err != nil {
			continue
		}
		if results == nil || len(*results) == 0 {
			continue
		}
		for _, r := range (*results)[0].Result {
			edges = append(edges, r.toCodeEdge(types.EdgeKind(table)))
		}
	}

	return edges, nil
}

// safeTime dereferences a time pointer, returning zero time if nil.
func safeTime(t *time.Time) time.Time {
	if t == nil {
		return time.Time{}
	}
	return *t
}

// edgeRow for temporal edge queries.
type edgeRow struct {
	In               *models.RecordID  `json:"in"`
	Out              *models.RecordID  `json:"out"`
	CallSite         string            `json:"call_site"`
	CallType         string            `json:"call_type"`
	IsDynamic        bool              `json:"is_dynamic"`
	IntroducedCommit string            `json:"introduced_commit"`
	Metadata         map[string]string `json:"metadata"`
}

func (r edgeRow) toCodeEdge(kind types.EdgeKind) types.CodeEdge {
	fromID := ""
	toID := ""
	if r.In != nil {
		fromID = fmt.Sprintf("%s:%v", r.In.Table, r.In.ID)
	}
	if r.Out != nil {
		toID = fmt.Sprintf("%s:%v", r.Out.Table, r.Out.ID)
	}
	return types.CodeEdge{
		Kind:             kind,
		FromID:           fromID,
		ToID:             toID,
		CallSite:         r.CallSite,
		CallType:         r.CallType,
		IsDynamic:        r.IsDynamic,
		IntroducedCommit: r.IntroducedCommit,
		Metadata:         r.Metadata,
	}
}
